spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microcloud-config-EureKa-client
server:
  port: 7004
eureka:
  instance:                    #EureKa 实例的定义
    hostname: eureKa-7004.com  #定义EureKa实例所在的主机名称
  client:                      #在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
    register-with-eureka: false   #false 表示当前的服务器不注册到eureKa 
    fetch-registry: false         #不从eureKa服务中获取信息
    service-url:
      defaultZone: http://eurekaDev:eurekaDev@eureka-7004.com:7004/eureka/
security:
  basic:
    enabled: true #启动安全认证
  user:
    name: eurekaDev
    password: eurekaDev

---
spring:
  profiles: bate
  application:
    name: microcloud-config-EureKa-client
server:
  port: 7004
eureka:
  instance:                    #EureKa 实例的定义
    hostname: eureKa-7004.com  #定义EureKa实例所在的主机名称
  client:                      #在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
    register-with-eureka: false   #false 表示当前的服务器不注册到eureKa 
    fetch-registry: false         #不从eureKa服务中获取信息
    service-url:
      defaultZone: http://eurekaBate:eurekaBate@eureka-7004.com:7004/eureka/
security:
  basic:
    enabled: true #启动安全认证
  user:
    name: eurekaBate
    password: eurekaBate
